// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Hhsqtms7Qm_HX7zJmwpkcmrS8NEIQ3o',
    appId: '1:444495292216:web:f13da15b1847540caa43cd',
    messagingSenderId: '444495292216',
    projectId: 'pet-app-qrcode',
    authDomain: 'pet-app-qrcode.firebaseapp.com',
    storageBucket: 'pet-app-qrcode.appspot.com',
    measurementId: 'G-6TLRN7V71V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuQqrZa7qvDmkukxDFSg3bxpJHw7PPjo',
    appId: '1:444495292216:android:c1291d38c15d8c04aa43cd',
    messagingSenderId: '444495292216',
    projectId: 'pet-app-qrcode',
    storageBucket: 'pet-app-qrcode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf22VNUX1bqNWzMpAhn1HyTi_HEK31KRs',
    appId: '1:444495292216:ios:5f54239f3e803954aa43cd',
    messagingSenderId: '444495292216',
    projectId: 'pet-app-qrcode',
    storageBucket: 'pet-app-qrcode.appspot.com',
    iosClientId: '444495292216-7oiue6dtg19mp408mmpqs28hvvslucpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAppQrcode',
  );
}
